version: '3.3'
services:
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phase3_shopping_app
    ports:
      - 3307:3306
    restart: always

  mysql-customer-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phase3_shopping_app_customer_db
    ports:
      - 3308:3306
    restart: always
    
  e-shopping-eureka-server-app:
    build: ./backend/e-shopping-eureka-server-app/ 
    ports:
      - 8761:8761
    restart: always

  springboot-admin-container:
    build: ./backend/e-shopping-admin-app/   
    depends_on:
      - mysql-container
      - mysql-customer-container
      - e-shopping-eureka-server-app
    environment:
      EUREKA_SERVER_URL: http://e-shopping-eureka-server-app:8761/eureka/
    ports:
      - 8181:8181
    restart: always

  springboot-customer-container:
    build: ./backend/e-shopping-customer-app/   
    depends_on:
      - mysql-container
      - mysql-customer-container
      - e-shopping-eureka-server-app
    environment:
      EUREKA_SERVER_URL: http://e-shopping-eureka-server-app:8761/eureka/
    ports:
      - 8282:8282
    restart: always  

  angular-admin-container:
    build: ./frontend/e-shopping-admin-app/
    ports:
      - 80:80
    restart: always 

  angular-user-container:
    build: ./frontend/e-shoppint-user-app/
    ports:
      - 8081:80
    restart: always 